/// One row per customer with churn, subscription, experience, value, and risk attributes.
table Customers
	lineageTag: 0ca2b014-2d36-400b-a7ef-1adf57a333db

	/// Unique customers in the current filter context.
	measure 'Total Customers' = DISTINCTCOUNT(Customers[CustomerID])
		formatString: #,##0
		displayFolder: Customer KPIs
		lineageTag: cfc91bf9-5e15-48ba-82c9-4259c1e5d5c7

	/// Customers whose current status is Active.
	measure 'Active Customers' = CALCULATE([Total Customers], KEEPFILTERS(Customers[CustomerStatus] = "Active"))
		formatString: #,##0
		displayFolder: Customer KPIs
		lineageTag: 7dee88b7-a131-4d2f-b3e5-a3f3d68251c3

	/// Customers whose current status is Churned.
	measure 'Churned Customers' = CALCULATE([Total Customers], KEEPFILTERS(Customers[CustomerStatus] = "Churned"))
		formatString: #,##0
		displayFolder: Customer KPIs
		lineageTag: e2febce6-04e0-4165-8fbb-be68ab6757ce

	/// Share of customers who have churned.
	measure 'Churn Rate' = DIVIDE([Churned Customers], [Total Customers])
		formatString: 0.0%
		displayFolder: Customer KPIs
		lineageTag: f7c28828-1dbc-4ed1-84ef-5defcd251c2f

	/// Share of customers who remain active.
	measure 'Retention Rate' = DIVIDE([Active Customers], [Total Customers])
		formatString: 0.0%
		displayFolder: Customer KPIs
		lineageTag: b91a552e-3a0c-4129-9efe-f75b6c8a6b3b

	/// Annualized recurring revenue lost from churned customers.
	measure 'Revenue Lost' = SUMX(FILTER(Customers, Customers[CustomerStatus] = "Churned"), Customers[MonthlyCharges] * 12)
		formatString: $#,##0
		displayFolder: Revenue KPIs
		lineageTag: 2fce64eb-49eb-496c-af1a-56f640cbe771

	/// Average historical revenue generated per customer.
	measure 'Average Customer Value' = DIVIDE(SUM(Customers[TotalRevenue]), [Total Customers])
		formatString: $#,##0
		displayFolder: Revenue KPIs
		lineageTag: f31bf803-db5d-4017-a846-92b0b2d001fd

	/// Average length of the customer relationship in months.
	measure 'Average Customer Tenure' = AVERAGE(Customers[TenureMonths])
		formatString: #,##0.0
		displayFolder: Customer KPIs
		lineageTag: 17f7dc14-922f-45ed-9c1a-d80404f197b1

	/// Active customers currently classified as High Risk.
	measure 'At-Risk Customers' = CALCULATE([Total Customers], KEEPFILTERS(Customers[CustomerStatus] = "Active"), KEEPFILTERS(Customers[RiskCategory] = "High Risk"))
		formatString: #,##0
		displayFolder: Risk KPIs
		lineageTag: aa18f7d3-70b4-497f-b375-088db8f84785

	/// Share of active customers currently classified as High Risk.
	measure 'High-Risk Customer Rate' = DIVIDE([At-Risk Customers], [Active Customers])
		formatString: 0.0%
		displayFolder: Risk KPIs
		lineageTag: 78cc1d06-1345-444a-bef3-3e54a54609a3

	/// Annualized recurring revenue generated by active customers.
	measure 'Annual Active Revenue' = SUMX(FILTER(Customers, Customers[CustomerStatus] = "Active"), Customers[MonthlyCharges] * 12)
		formatString: $#,##0
		displayFolder: Revenue KPIs
		lineageTag: e7ade991-ba5a-4059-bd37-6145fb21c542

	/// Annualized recurring revenue attached to active High Risk customers.
	measure 'Revenue at Risk' = SUMX(FILTER(Customers, Customers[CustomerStatus] = "Active" && Customers[RiskCategory] = "High Risk"), Customers[MonthlyCharges] * 12)
		formatString: $#,##0
		displayFolder: Risk KPIs
		lineageTag: 64cf3f98-6c42-4b14-8533-ab0139dc0572

	/// Customers who churned during the selected date period.
	measure 'Monthly Churned Customers' = CALCULATE([Churned Customers], USERELATIONSHIP('Date'[Date], Customers[ChurnDate]))
		formatString: #,##0
		displayFolder: Trend KPIs
		lineageTag: fcfb3516-a13d-455f-8df0-fcb41cc58d25

	/// Customers who churned during a period divided by customers active at the period start.
	measure 'Monthly Churn Rate' =
			VAR _PeriodStart = MIN('Date'[Date])
			VAR _CustomersAtStart =
				CALCULATE(
					DISTINCTCOUNT(Customers[CustomerID]),
					REMOVEFILTERS('Date'),
					FILTER(
						Customers,
						Customers[JoinDate] < _PeriodStart
							&& (ISBLANK(Customers[ChurnDate]) || Customers[ChurnDate] >= _PeriodStart)
					)
				)
			RETURN DIVIDE([Monthly Churned Customers], _CustomersAtStart)
		formatString: 0.0%
		displayFolder: Trend KPIs
		lineageTag: 829cacf9-94d2-4331-bd3c-474c3b8f0e7e

	/// Average monthly charge in the current customer segment.
	measure 'Average Monthly Charge' = AVERAGE(Customers[MonthlyCharges])
		formatString: $#,##0.00
		displayFolder: Revenue KPIs
		lineageTag: 5a8b3207-7655-426d-b77c-4f23b4c51c6d

	/// Average rule-based churn risk score.
	measure 'Average Risk Score' = AVERAGE(Customers[RiskScore])
		formatString: #,##0.0
		displayFolder: Risk KPIs
		lineageTag: 8d1316dc-440c-4d76-88a8-759cb9540ef7

	column CustomerID
		dataType: string
		lineageTag: fab60be0-7d2e-4ba5-91b3-cd6f9e292f57
		summarizeBy: none
		sourceColumn: CustomerID

	column JoinDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 71b91f88-8b47-4484-8f21-d8304f00f755
		summarizeBy: none
		sourceColumn: JoinDate

		annotation UnderlyingDateTimeDataType = Date

	column ChurnDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: f226f62e-d2ab-4251-a0fb-3f3f08ed569e
		summarizeBy: none
		sourceColumn: ChurnDate

		annotation UnderlyingDateTimeDataType = Date

	column CustomerStatus
		dataType: string
		lineageTag: 8e864087-2a6b-4424-8b0f-0ba146255a4b
		summarizeBy: none
		sourceColumn: CustomerStatus

	column Age
		dataType: int64
		formatString: 0
		lineageTag: c5662327-1d2a-4a77-8c0b-bc39f6cc4844
		summarizeBy: none
		sourceColumn: Age

	column AgeGroup
		dataType: string
		lineageTag: f7119c26-f26f-4615-9e25-4bac8f336472
		summarizeBy: none
		sourceColumn: AgeGroup

	column Gender
		dataType: string
		lineageTag: fc1d2fc5-4358-4d68-a239-6af85ba0ee83
		summarizeBy: none
		sourceColumn: Gender

	column Geography
		dataType: string
		lineageTag: 497c1ef7-5be8-4d88-819f-d6c6ee49dc22
		summarizeBy: none
		sourceColumn: Geography

	column TenureMonths
		dataType: int64
		formatString: 0
		lineageTag: 093a430e-ba72-4a3d-9cf2-f00bf9e0bdcf
		summarizeBy: none
		sourceColumn: TenureMonths

	column TenureBand
		dataType: string
		lineageTag: c3a6a224-2bb7-4e56-8fb5-e1cb5dee976a
		summarizeBy: none
		sourceColumn: TenureBand

	column IncomeLevel
		dataType: string
		lineageTag: 57c8fa27-b8ff-4805-a841-29a6a91ac404
		summarizeBy: none
		sourceColumn: IncomeLevel

	column ContractType
		dataType: string
		lineageTag: d393fcde-c332-4a1e-8e96-412d146a7094
		summarizeBy: none
		sourceColumn: ContractType

	column SubscriptionPlan
		dataType: string
		lineageTag: 610acee7-4041-451a-bcc9-e94202c0c40e
		summarizeBy: none
		sourceColumn: SubscriptionPlan

	column MonthlyCharges
		dataType: decimal
		formatString: $#,##0.00
		lineageTag: 1cd7c152-39bb-4336-8532-062279e911b1
		summarizeBy: sum
		sourceColumn: MonthlyCharges

	column MonthlyChargeBand
		dataType: string
		lineageTag: f67c45f7-e978-4fb6-b505-b447021d4d32
		summarizeBy: none
		sourceColumn: MonthlyChargeBand

	column PaymentMethod
		dataType: string
		lineageTag: 7797135f-f299-4571-ab6f-465b8eee44fb
		summarizeBy: none
		sourceColumn: PaymentMethod

	column AutoPay
		dataType: string
		lineageTag: e7e16114-1964-417d-87f9-797bfbb399ff
		summarizeBy: none
		sourceColumn: AutoPay

	column SupportCalls
		dataType: int64
		formatString: 0
		lineageTag: 7fcd96cb-1284-4b16-821a-7416c9112b22
		summarizeBy: sum
		sourceColumn: SupportCalls

	column LatePayments
		dataType: int64
		formatString: 0
		lineageTag: a97ad78f-93f4-4ba2-9d41-4a93d85b5588
		summarizeBy: sum
		sourceColumn: LatePayments

	column SatisfactionScore
		dataType: int64
		formatString: 0
		lineageTag: b3681ad4-fa4c-40a9-95b6-50940478d09f
		summarizeBy: average
		sourceColumn: SatisfactionScore

	column TotalRevenue
		dataType: decimal
		formatString: $#,##0.00
		lineageTag: 15586c21-7af7-46e3-a2dc-ac3a8f65c904
		summarizeBy: sum
		sourceColumn: TotalRevenue

	column CustomerValueSegment
		dataType: string
		lineageTag: 1a0348f3-8721-42c8-9360-3008f4077c92
		summarizeBy: none
		sourceColumn: CustomerValueSegment

	column LastActivityDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 81f79804-78c7-40e6-9bad-edb9bc579a1e
		summarizeBy: none
		sourceColumn: LastActivityDate

		annotation UnderlyingDateTimeDataType = Date

	column RiskScore
		dataType: int64
		formatString: 0
		lineageTag: 7264825d-5943-4933-8674-1e00a4090f8e
		summarizeBy: average
		sourceColumn: RiskScore

	column RiskCategory
		dataType: string
		lineageTag: 26f8998e-3aab-4f6e-b79e-78979a257de1
		summarizeBy: none
		sourceColumn: RiskCategory

	column ChurnReason
		dataType: string
		lineageTag: feb22392-b883-4856-9241-f1e0a741902e
		summarizeBy: none
		sourceColumn: ChurnReason

	partition Customers = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("D:\MY PORTFOLIO\PowerBI project\data\Customers.csv"), [Delimiter=",", Columns=23, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
						{"CustomerID", type text}, {"JoinDate", type date}, {"ChurnDate", type date},
						{"CustomerStatus", type text}, {"Age", Int64.Type}, {"AgeGroup", type text},
						{"Gender", type text}, {"Geography", type text}, {"TenureMonths", Int64.Type},
						{"IncomeLevel", type text}, {"ContractType", type text}, {"SubscriptionPlan", type text},
						{"MonthlyCharges", Currency.Type}, {"PaymentMethod", type text}, {"AutoPay", type text},
						{"SupportCalls", Int64.Type}, {"LatePayments", Int64.Type}, {"SatisfactionScore", Int64.Type},
						{"TotalRevenue", Currency.Type}, {"LastActivityDate", type date}, {"RiskScore", Int64.Type},
						{"RiskCategory", type text}, {"ChurnReason", type text}
					}),
					CleanedText = Table.TransformColumns(ChangedTypes, {
						{"CustomerID", Text.Trim, type text}, {"CustomerStatus", Text.Trim, type text},
						{"Gender", Text.Trim, type text}, {"Geography", Text.Trim, type text},
						{"ContractType", Text.Trim, type text}, {"SubscriptionPlan", Text.Trim, type text},
						{"PaymentMethod", Text.Trim, type text}, {"AutoPay", Text.Trim, type text}
					}),
					RemovedDuplicates = Table.Distinct(CleanedText, {"CustomerID"}),
					AddedTenureBand = Table.AddColumn(RemovedDuplicates, "TenureBand", each if [TenureMonths] <= 12 then "0-12 Months" else if [TenureMonths] <= 24 then "13-24 Months" else if [TenureMonths] <= 36 then "25-36 Months" else "37+ Months", type text),
					AddedChargeBand = Table.AddColumn(AddedTenureBand, "MonthlyChargeBand", each if [MonthlyCharges] < 60 then "Low (<$60)" else if [MonthlyCharges] < 90 then "Medium ($60-$89)" else "High ($90+)", type text),
					AddedValueSegment = Table.AddColumn(AddedChargeBand, "CustomerValueSegment", each if [TotalRevenue] < 1000 then "Low Value" else if [TotalRevenue] < 2500 then "Medium Value" else "High Value", type text)
				in
					AddedValueSegment

